path: '/home/smebellis/CIS583_ALPR_Final_project_3-24-2024/data'
train: 'train'
val: 'valid'
test: 'test'

# Classes
names:
  0: 'License_Plate'

# Configuration for License Plate Detection Project
model_paths:
  coco_model: "/home/smebellis/CIS583_ALPR_Final_project_3-24-2024/models/yolov8n.pt"
  license_plate_detector: "/home/smebellis/CIS583_ALPR_Final_project_3-24-2024/models/license_plate_detector.pt"

video_path: "/home/smebellis/CIS583_ALPR_Final_project_3-24-2024/videos/sample.mp4"


interpolated_csv_path: "/home/smebellis/CIS583_ALPR_Final_project_3-24-2024/test_interpolated.csv"
